server:
  port: 8080

spring:
  application:
    name: enterprise-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise_platform
    username: enterprise
    password: enterprise123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        hibernate.format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} traceId=%X{traceId} - %msg%n"

app:
  jwt:
    secret: "EnterprisePlatformJwtSecretKeyMustBeLongEnough_ChangeMe_1234567890"
    expire-seconds: 28800   # 8小时
